<?php
if (!defined('ABSPATH')) {
    exit;
}
$coursetransit_settings = $settings ?? [];
$coursetransit_pro_active = (bool) apply_filters('coursetransit_pro_active', false);
?>

<!-- PAGE HEADER -->
<div class="page-header row no-gutters py-4" style="padding-top: 0 !important; padding-bottom: 0 !important;">
    <div class="col-6">
        <h3 class="page-title">Settings</h3>
    </div>
</div>

<!-- TABS -->
<ul class="nav nav-tabs mb-3 mt-3" id="coursetransitTabs" role="tablist">

    <li class="nav-item" role="presentation">
        <button class="nav-link active" id="general-tab" data-bs-toggle="tab" data-bs-target="#tab-general"
            type="button" role="tab">
            General
        </button>
    </li>

    <?php do_action('coursetransit_settings_tabs_after_general'); ?>

    <li class="nav-item" role="presentation">
        <button class="nav-link" id="sync-tab" data-bs-toggle="tab" data-bs-target="#tab-sync" type="button" role="tab">
            Synchronization
        </button>
    </li>

    <?php if (!$coursetransit_pro_active): ?>
    <li class="nav-item" role="presentation">
        <button class="nav-link coursetransit-pro-feature-trigger" id="sso-tab" data-pro-feature="sso" type="button" role="tab">
            SSO <span class="badge bg-warning text-dark ms-1">PRO</span>
        </button>
    </li>
    <?php endif; ?>

    <li class="nav-item" role="presentation">
        <?php if ($coursetransit_pro_active): ?>
            <button class="nav-link" id="bulk-tab" data-bs-toggle="tab" data-bs-target="#tab-bulk" type="button" role="tab">Bulk Purchase</button>
        <?php else: ?>
            <button class="nav-link coursetransit-pro-feature-trigger" id="bulk-tab" data-pro-feature="bulk-purchase" type="button" role="tab">Bulk Purchase <span class="badge bg-warning text-dark ms-1">PRO</span></button>
        <?php endif; ?>
    </li>

    <li class="nav-item" role="presentation">
        <button class="nav-link" id="logs-tab" data-bs-toggle="tab" data-bs-target="#tab-logs" type="button" role="tab">
            Logs
        </button>
    </li>

</ul>

<!-- CARD WITH TABS -->
<div class="card" style="max-width: 100% !important;">

    <!-- CARD BODY = TAB CONTENT -->
    <div class="card-body tab-content">

        <!-- GENERAL -->
        <div class="tab-pane fade show active" id="tab-general" role="tabpanel">
            <div class="row">

                <div class="col-lg-6 col-md-12" style="margin-left: -30px;">

                    <!-- HEADING -->
                    <h5>
                        Moodle Connection
                    </h5>

                    <p class="text-muted" style="font-size:13px;">
                        Enter your Moodle site URL (e.g. https://lms.example.com)
                        and the API token generated by the CourseTransit plugin
                        in your Moodle Application.
                    </p>

                    <div id="coursetransit-settings-result" class="alert d-none mt-3" role="alert">
                    </div>

                    <form id="coursetransit-settings-form">

                        <?php wp_nonce_field('coursetransit_settings_nonce'); ?>

                        <div class="form-group coursetransit-sync-setting-group">

                            <label class="coursetransit-sync-label">
                                Moodle Site URL
                            </label>

                            <input type="url" class="form-control coursetransit-sync-control"
                                name="settings[moodle_url]" required
                                value="<?php echo esc_attr($coursetransit_settings['moodle_url'] ?? ''); ?>">

                        </div>

                        <div class="form-group coursetransit-sync-setting-group">

                            <label class="coursetransit-sync-label">
                                Web Service Token
                            </label>

                            <input type="text" class="form-control coursetransit-sync-control"
                                name="settings[moodle_token]" required
                                value="<?php echo esc_attr($coursetransit_settings['moodle_token'] ?? ''); ?>">

                        </div>

                        <div class="d-flex flex-wrap gap-2 mt-4">

                            <button type="submit" class="button button-primary">

                                Save Settings

                            </button>

                            <button id="coursetransit-test-connection" class="button button-secondary">

                                Test Connection

                            </button>

                        </div>

                    </form>

                </div>

            </div>
        </div>

        <?php do_action('coursetransit_settings_content_after_general'); ?>

        <!-- SYNCHRONIZATION -->
        <div class="tab-pane fade" id="tab-sync" role="tabpanel">

            <div class="row">
                <div class="col-lg-12 coursetransit-sync-settings-wrapper" style="margin-left: -30px;">

                    <h5>
                        Synchronization Settings
                    </h5>

                    <div class="row g-4">

                        <!-- ENROLLMENT -->
                        <div class="col-lg-6 col-md-12">

                            <label class="ct-setting-label">
                                Default Enrollment Period
                                <span class="ct-setting-help">
                                    <i class="material-icons" style="font-size:14px;">info</i>
                                    <span class="ct-tooltip">
                                        Sets the default enrollment duration for newly synced Moodle courses. Individual
                                        courses can override this value.
                                    </span>
                                </span>
                            </label>

                            <select id="cts-default-enrollment-period" class="form-control coursetransit-sync-control">

                                <option value="0">Lifetime Access</option>
                                <option value="30">30 Days</option>
                                <option value="60">60 Days</option>
                                <option value="90">90 Days</option>
                                <option value="180">180 Days</option>
                                <option value="365">365 Days</option>

                            </select>

                        </div>

                        <!-- PRODUCT STATUS -->
                        <div class="col-lg-6 col-md-12">
                            <label class="ct-setting-label">
                                Product Status
                                <span class="ct-setting-help">
                                    <i class="material-icons" style="font-size:14px;">info</i>
                                    <span class="ct-tooltip">
                                        Choose the WooCommerce product status assigned when new courses are created.
                                    </span>
                                </span>
                            </label>

                            <select id="cts-product-status" class="form-control coursetransit-sync-control">

                                <option value="publish">
                                    Publish Immediately
                                </option>

                                <option value="draft">
                                    Save as Draft
                                </option>

                                <option value="private">
                                    Private
                                </option>

                            </select>

                        </div>

                        <!-- PRODUCT CONTENT SYNC -->
                        <div class="col-lg-6 col-md-12">
                            <label class="ct-setting-label">
                                Product Content Sync
                                <span class="ct-setting-help">
                                    <i class="material-icons" style="font-size:14px;">info</i>
                                    <span class="ct-tooltip">
                                        Controls whether product titles, descriptions, and short descriptions are
                                        synchronized during future course synchronizations.
                                    </span>
                                </span>
                            </label>

                            <select id="cts-product-content-sync" class="form-control coursetransit-sync-control">

                                <option value="all">
                                    Update Existing & New Products
                                </option>

                                <option value="new">
                                    Sync Only During Product Creation
                                </option>

                            </select>

                        </div>

                        <!-- CURRICULUM SYNC -->
                        <div class="col-lg-6 col-md-12">
                            <label class="ct-setting-label">
                                Curriculum & Activities Sync
                                <span class="ct-setting-help">
                                    <i class="material-icons" style="font-size:14px;">info</i>
                                    <span class="ct-tooltip">
                                        Synchronizes Moodle sections, lessons, activities, and resources into the linked
                                        WooCommerce product.
                                    </span>
                                </span>
                            </label>

                            <select id="cts-sync-curriculum" class="form-control coursetransit-sync-control">

                                <option value="all">
                                    Update Existing & New Products
                                </option>

                                <option value="new">
                                    Sync Only During Product Creation
                                </option>

                                <option value="disabled">
                                    Disable Curriculum Sync
                                </option>

                            </select>

                        </div>

                        <!-- CATEGORY SYNC -->
                        <div class="col-lg-6 col-md-12">
                            <label class="ct-setting-label">
                                Category Sync
                                <span class="ct-setting-help">
                                    <i class="material-icons" style="font-size:14px;">info</i>
                                    <span class="ct-tooltip">
                                        Automatically creates and updates WooCommerce product categories based on Moodle
                                        course categories.
                                    </span>
                                </span>
                            </label>
                            <select id="cts-category-sync" class="form-control coursetransit-sync-control">

                                <option value="all">
                                    Update Existing & New Products
                                </option>

                                <option value="new">
                                    Sync Only During Product Creation
                                </option>

                                <option value="disabled">
                                    Disable Category Sync
                                </option>

                            </select>

                        </div>

                        <!-- IMAGE SYNC -->
                        <div class="col-lg-6 col-md-12">
                            <label class="ct-setting-label">
                                Course Images
                                <span class="ct-setting-help">
                                    <i class="material-icons" style="font-size:14px;">info</i>
                                    <span class="ct-tooltip">
                                        Controls how featured images are imported and updated from Moodle courses.
                                    </span>
                                </span>
                            </label>

                            <select id="cts-image-sync" class="form-control coursetransit-sync-control">

                                <option value="all">
                                    Update Existing & New Products
                                </option>

                                <option value="new">
                                    Sync Only During Product Creation
                                </option>

                                <option value="keep_existing">
                                    Keep Existing Product Images
                                </option>

                                <option value="disabled">
                                    Disable Image Sync
                                </option>

                            </select>

                        </div>

                        <!-- MISSING COURSES -->
                        <div class="col-lg-6 col-md-12">

                            <label class="ct-setting-label">
                                Missing Moodle Courses
                                <span class="ct-setting-help">
                                    <i class="material-icons" style="font-size:14px;">info</i>
                                    <span class="ct-tooltip">
                                        Choose what happens to WooCommerce products when their linked Moodle course no
                                        longer exists.
                                    </span>
                                </span>
                            </label>

                            <select id="cts-missing-course-action" class="form-control coursetransit-sync-control">

                                <option value="draft">
                                    Mark Product Draft
                                </option>

                                <option value="trash">
                                    Trash Product
                                </option>

                                <option value="keep">
                                    Keep Product Published
                                </option>

                            </select>

                        </div>

                        <!-- AUTOMATIC COURSE SYNC -->
        <div class="col-lg-6 col-md-12">
            <?php ob_start(); do_action('coursetransit_settings_auto_sync_field'); $coursetransit_auto_sync_content = ob_get_clean(); ?>
            <?php if ($coursetransit_auto_sync_content !== ''): ?>
                <?php echo $coursetransit_auto_sync_content; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Add-on owns its trusted settings markup. ?>
            <?php else: ?>
                <label class="ct-setting-label d-flex align-items-center justify-content-between">
                    <span>
                        Automatic Course Sync
                        <?php if (!$coursetransit_pro_active): ?>
                            <span class="badge bg-warning text-dark ms-1">PRO</span>
                        <?php endif; ?>
                    </span>
                </label>
                <button type="button" class="button button-secondary w-100 coursetransit-pro-feature-trigger"
                    data-pro-feature="automatic-sync">
                    Unlock Automatic Sync
                </button>
                <small class="text-muted d-block mt-2">
                    Automatically process Moodle webhook events and keep courses synchronized without manual syncing.
                </small>
            <?php endif; ?>
        </div>

        <!-- ACTIONS -->
                        <div class="col-12">

                            <div class="coursetransit-sync-actions">

                                <button type="button" id="cts-settings-save" class="button button-primary">

                                    Save Settings

                                </button>

                            </div>

                        </div>

                    </div>

                </div>
            </div>

        </div>

        <!-- SSO -->
        <?php if (!$coursetransit_pro_active): ?>
        <div class="tab-pane fade" id="tab-sso" role="tabpanel">
            <?php ob_start(); do_action('coursetransit_settings_sso_content'); $coursetransit_sso_content = ob_get_clean(); ?>
            <?php if ($coursetransit_sso_content !== ''): ?>
                <?php echo $coursetransit_sso_content; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Add-on owns its trusted settings markup. ?>
            <?php else: ?>
                <h5>
                    Single Sign-On (SSO)
                    <span class="badge bg-warning text-dark">PRO</span>
                </h5>
                <p class="text-muted" style="font-size:13px;">
                    Single Sign-On (SSO) is available in the Pro version of CourseTransit.
                </p>
            <?php endif; ?>
        </div>
        <?php endif; ?>

        <!-- BULK PURCHASE -->
        <div class="tab-pane fade" id="tab-bulk" role="tabpanel">
            <?php ob_start(); do_action('coursetransit_settings_bulk_content'); $coursetransit_bulk_content = ob_get_clean(); ?>
            <?php if ($coursetransit_bulk_content !== ''): ?>
                <?php echo $coursetransit_bulk_content; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Add-on owns its trusted settings markup. ?>
            <?php elseif (!$coursetransit_pro_active): ?>
                <h5>
                    Bulk Purchase
                    <span class="badge bg-warning text-dark">PRO</span>
                </h5>
                <p class="text-muted" style="font-size:13px;">
                    Bulk Purchase, quantity-based discounts, and Request a Quote are available in the Pro version of CourseTransit.
                </p>
                <button type="button" class="button button-primary coursetransit-pro-feature-trigger" data-pro-feature="bulk-purchase">
                    Upgrade to CourseTransit Pro
                </button>
            <?php else: ?>
                <p class="text-muted">Bulk Purchase settings could not be loaded. Please reload the page.</p>
            <?php endif; ?>
        </div>

        <!-- LOGS -->
        <div class="tab-pane fade" id="tab-logs" role="tabpanel">

            <!-- HEADER -->
            <div class="mb-4">

                <h5>
                    Log
                </h5>

                <p class="text-muted mb-0" style="font-size:13px;">
                    Review all system logs and errors.
                </p>

            </div>

            <div class="card mb-3 cts-log-settings-card" style="max-width:100% !important;">

                <div class="card-body">

                    <div class="cts-toggle-row">

                        <div>

                            <div class="cts-toggle-title" style="margin-left: -20px">
                                Enable System Logging
                            </div>

                            <div class="cts-toggle-description" style="margin-left: -20px">
                                Store sync events,
                                enrollments and system errors
                                for troubleshooting.
                            </div>

                        </div>

                        <div class="d-flex align-items-center gap-2" style="margin-right: -20px;">

                            <span id="cts-log-status-text" class="cts-toggle-status">
                                Disabled
                            </span>

                            <label class="cts-switch mb-0">

                                <input type="checkbox" id="cts-log-enabled">

                                <span class="cts-slider"></span>

                            </label>

                        </div>

                    </div>

                </div>

            </div>

            <div class="table-responsive">

                <table id="coursetransit-logs-table" class="table table-striped table-bordered w-100 mb-0">

                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Level</th>
                            <th>Title</th>
                            <th>Status</th>
                            <th>Date</th>
                            <th>Actions</th>
                        </tr>
                    </thead>

                </table>

            </div>

        </div>

    </div>
</div>

<div class="modal fade" id="ctsLogViewModal" tabindex="-1" role="dialog" aria-hidden="true">

    <div class="modal-dialog modal-lg" role="document">

        <div class="modal-content">

            <div class="modal-header">

                <h5 class="modal-title">
                    Log Details
                </h5>

                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>

            </div>

            <div class="modal-body">

                <pre id="cts-log-context" style="
                        max-height:500px;
                        overflow:auto;
                        background:#f8fafc;
                        border:1px solid #e5e7eb;
                        border-radius:8px;
                        padding:16px;
                        font-size:12px;
                        line-height:1.6;
                        margin:0;
                    "></pre>

            </div>

        </div>

    </div>

</div>