<?php
if (!defined('ABSPATH')) {
    exit;
}
$coursetransit_settings = $settings ?? [];
?>

<!-- PAGE HEADER -->
<div class="page-header row no-gutters py-4" style="padding-top: 0 !important; padding-bottom: 0 !important;">
    <div class="col-6">
        <h3 class="page-title">Settings</h3>
    </div>
</div>

<!-- CARD WITH TABS -->
<div class="card" style="max-width: 100% !important;">

    <!-- CARD BODY = TAB CONTENT -->
    <div class="card-body tab-content">

        <!-- GENERAL -->
        <div class="tab-pane fade show active" id="tab-general" role="tabpanel">
            <div class="row">
                <div class="col-lg-6 col-md-12" style="margin-left: -30px;">

                    <!-- <h6 class="mb-3">Moodle Settings</h6> -->

                    <p class="text-muted" style="font-size:13px;">
                        Enter your Moodle site URL (e.g. https://lms.example.com) and the API token generated by the
                        CourseTransit plugin in your Moodle Application.
                    </p>

                    <div id="coursetransit-settings-result" class="alert d-none mt-3" role="alert">
                    </div>

                    <form id="coursetransit-settings-form">

                        <?php wp_nonce_field('coursetransit_settings_nonce'); ?>

                        <div class="form-group">
                            <label>Moodle Site URL</label>
                            <input type="url" class="form-control" name="settings[moodle_url]" required
                                value="<?php echo esc_attr($coursetransit_settings['moodle_url'] ?? ''); ?>">
                        </div>

                        <div class="form-group">
                            <label>Web Service Token</label>
                            <input type="text" class="form-control" name="settings[moodle_token]" required
                                value="<?php echo esc_attr($coursetransit_settings['moodle_token'] ?? ''); ?>">
                        </div>

                        <div class="d-flex flex-wrap gap-2 mt-4">
                            <button type="submit" class="button button-primary">
                                Save Settings
                            </button>

                            <button id="coursetransit-test-connection" class="button button-secondary">
                                Test Connection
                            </button>
                        </div>
                    </form>

                </div>
            </div>
        </div>


    </div>
</div>